builds:
  # List of builds
- # First Build
  env:
    - CGO_ENABLED=0
  main: main.go
  # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
  binary: bin/{{ .ProjectName }}
  goos:
    - freebsd
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
  goarm:
    - 5
    - 6
    - 7
  ignore:
      # TODO: add freebsd/arm support to gopsutil
    - goos: freebsd
      goarch: arm
  targets:
    - linux_386
    - linux_amd64
    - linux_arm_5
    - linux_arm_6
    - linux_arm_7
    - linux_arm64
    # - freebsd_amd64
    # - freebsd_386
    - darwin_amd64
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
nfpms:
  -
    id: serverauth
    package_name: serverauth
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - serverauth-agent-dev
    vendor: ServerAuth.com
    homepage: https://serverauth.com
    maintainer: ServerAuth <info@serverauth.com>
    description: ServerAuth management agent.
    formats:
        - deb
        - rpm
    dependencies:
        - git
    epoch: 1
    release: 2
    empty_folders:
        - /etc/serverauth